"""Add dates to matches table

Revision ID: 04d6ca6fd2bf
Revises: 8e7045ae63af
Create Date: 2025-06-11 12:50:39.729291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d6ca6fd2bf'
down_revision: Union[str, None] = '8e7045ae63af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('matches', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'updated_at')
    op.drop_column('matches', 'created_at')
    # ### end Alembic commands ###
