"""add profile id

Revision ID: 0e46d7824455
Revises: 257175848c51
Create Date: 2025-04-12 03:15:07.008839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e46d7824455'
down_revision: Union[str, None] = '257175848c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('siege_bans', sa.Column('profile_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_siege_bans_profile_id'), 'siege_bans', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_siege_bans_profile_id'), table_name='siege_bans')
    op.drop_column('siege_bans', 'profile_id')
    # ### end Alembic commands ###
