"""Initial migration

Revision ID: 257175848c51
Revises: 
Create Date: 2025-04-11 23:12:25.746755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '257175848c51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siege_bans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('uplay', sa.String(), nullable=True),
    sa.Column('psn', sa.String(), nullable=True),
    sa.Column('xbl', sa.String(), nullable=True),
    sa.Column('ban_reason', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_siege_bans_ban_reason'), 'siege_bans', ['ban_reason'], unique=False)
    op.create_index(op.f('ix_siege_bans_id'), 'siege_bans', ['id'], unique=True)
    op.create_index(op.f('ix_siege_bans_psn'), 'siege_bans', ['psn'], unique=False)
    op.create_index(op.f('ix_siege_bans_uplay'), 'siege_bans', ['uplay'], unique=False)
    op.create_index(op.f('ix_siege_bans_xbl'), 'siege_bans', ['xbl'], unique=False)
    op.create_table('siege_bans_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ban_id', sa.String(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=True),
    sa.Column('source_application_id', sa.String(), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('space_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ban_id'], ['siege_bans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_siege_bans_metadata_date_posted'), 'siege_bans_metadata', ['date_posted'], unique=False)
    op.create_index(op.f('ix_siege_bans_metadata_id'), 'siege_bans_metadata', ['id'], unique=True)
    op.create_index(op.f('ix_siege_bans_metadata_notification_type'), 'siege_bans_metadata', ['notification_type'], unique=False)
    op.create_index(op.f('ix_siege_bans_metadata_source_application_id'), 'siege_bans_metadata', ['source_application_id'], unique=False)
    op.create_index(op.f('ix_siege_bans_metadata_space_id'), 'siege_bans_metadata', ['space_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_siege_bans_metadata_space_id'), table_name='siege_bans_metadata')
    op.drop_index(op.f('ix_siege_bans_metadata_source_application_id'), table_name='siege_bans_metadata')
    op.drop_index(op.f('ix_siege_bans_metadata_notification_type'), table_name='siege_bans_metadata')
    op.drop_index(op.f('ix_siege_bans_metadata_id'), table_name='siege_bans_metadata')
    op.drop_index(op.f('ix_siege_bans_metadata_date_posted'), table_name='siege_bans_metadata')
    op.drop_table('siege_bans_metadata')
    op.drop_index(op.f('ix_siege_bans_xbl'), table_name='siege_bans')
    op.drop_index(op.f('ix_siege_bans_uplay'), table_name='siege_bans')
    op.drop_index(op.f('ix_siege_bans_psn'), table_name='siege_bans')
    op.drop_index(op.f('ix_siege_bans_id'), table_name='siege_bans')
    op.drop_index(op.f('ix_siege_bans_ban_reason'), table_name='siege_bans')
    op.drop_table('siege_bans')
    # ### end Alembic commands ###
