"""Get client version

Revision ID: 47f7f55a9c9b
Revises: 98458740f8f2
Create Date: 2025-06-11 13:02:25.600178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f7f55a9c9b'
down_revision: Union[str, None] = '98458740f8f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('current_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('current_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
