"""Add signature column to matches table

Revision ID: 627d723f8d40
Revises: ee9bba34d91e
Create Date: 2025-06-12 01:13:07.573382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '627d723f8d40'
down_revision: Union[str, None] = 'ee9bba34d91e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('signature', sa.String(), nullable=True))
    op.create_index(op.f('ix_matches_signature'), 'matches', ['signature'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_signature'), table_name='matches')
    op.drop_column('matches', 'signature')
    # ### end Alembic commands ###
