"""Add request client host to matches table

Revision ID: 98458740f8f2
Revises: 04d6ca6fd2bf
Create Date: 2025-06-11 12:53:33.525124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98458740f8f2'
down_revision: Union[str, None] = '04d6ca6fd2bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('created_by_host', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'created_by_host')
    # ### end Alembic commands ###
