"""Add client download url

Revision ID: ee9bba34d91e
Revises: 47f7f55a9c9b
Create Date: 2025-06-11 16:05:02.752667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9bba34d91e'
down_revision: Union[str, None] = '47f7f55a9c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('download_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'download_url')
    # ### end Alembic commands ###
